# yaml 配置
version: "3.7"
services:
  mysql:
    image: "mysql:latest"
    ports:
      - "13061:3306"
#    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "Han1373338025.."
#      MYSQL_DATABASE: "goweb"
      MYSQL_PASSWORD: "Han1373338025.."
#    volumes:
#      - ./init.sql:/data/application/init.sql
  redis:
    image: "redis:latest"
    ports:
      - "16379:6379"
  goweb:
    build: .
    command: sh -c "./wait-for.sh mysql:3306 redis:6379 -- ./goweb ./conf/config.yaml"
    depends_on:
      - mysql
      - redis
    ports:
      - "8084:8084"